config/routes.rb
Rails.application.routes.draw do


  root 'questions#index'
  resources :sessions
  resources :users


  resources :answers, only: [:edit, :destroy] do
    resources :comments, only: [:create]
  end

  resources :questions do
    resources :answers, only: [:new, :create]
    resources :comments, only: [:create, :index]
  end

  resources :categories, only: [:index, :show]

  resources :votes, only: [:create]

  get '/recent/questions', to: 'questions#recent'
  get '/trending/questions', to: 'questions#trending'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  has_many :votes, as: :voteable
  has_many :comments, as: :commentable

  validates :content, length: {minimum: 10}

  def incr_vote_count
    self.increment!(:vote_count)
  end

  def decr_vote_count
    self.decrement!(:vote_count)
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user
  has_many :questions
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  scope :with_user, -> {includes :user}
end

app/models/question.rb
class Question < ActiveRecord::Base

  belongs_to :user
  has_many :votes, as: :voteable
  has_many :answers
  has_many :comments, as: :commentable
  belongs_to :category

  scope :with_all_relations, -> (question_id) { includes(:user,
                                                         :category,
                                                         :comments => :user,
                                                         :answers => [:user,
                                                                      {:comments => :user}]
                                                          ).find(question_id) }

  def incr_vote_count
    self.increment!(:vote_count)
  end

  def decr_vote_count
    self.decrement!(:vote_count)
  end

  def self.trending
    all.sort {|a,b| b.past_week_trend <=> a.past_week_trend}
  end

  def past_week_trend
    past_week_answers + past_week_comments
  end

  private

  def past_week_answers
    answers.where('created_at >= :week_ago', week_ago: Time.now - 7.days).count
  end

  def past_week_comments
    comments.where('created_at >= :week_ago', week_ago: Time.now - 7.days).count
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email, uniqueness: true
  validates :username, uniqueness: true

  has_many :votes
  has_many :questions
  has_many :answers
  has_many :comments

  def karma
    question_karma + answer_karma + comment_karma
  end

  private

  def question_karma
    karma_weight = 2
    questions.map(&:vote_count).inject(0, &:+) * karma_weight
  end

  def answer_karma
    karma_weight = 4
    answers.map(&:vote_count).inject(0, &:+) * karma_weight
  end

  def comment_karma
    karma_weight = 0.5
    (comments.count * karma_weight).to_i
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  before_save :update_vote_count

  belongs_to :user
  belongs_to :voteable, polymorphic: true
  validates_uniqueness_of :voteable_id, scope: [:user_id, :voteable_type], message: "You already voted"
  validate :check_self_voting

  def check_self_voting
    if voteable.user.id == user_id
      errors.add(:user_id, "Can't vote on your own post")
    end
  end

  def update_vote_count
    if direction == 'Up'
      voteable.incr_vote_count
    elsif direction == 'Down'
      voteable.decr_vote_count
    end
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    question = Question.find(params[:question_id])
    answer = question.answers.new(content: params[:answer][:content], user_id: session[:user_id])
    redirect_to question
  end

  def edit
    @answer = Answer.find(params[:id])
  end

  def update
    answer = Answer.find(params[:id])
    question = answer.question
    if answer.update(content: params[:answer][:content])
      redirect_to question
    else
      redirect_to :back
    end
  end

  def delete
    answer = Answer.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def curr_user
    User.find(session[:user_id])
  end

  def curr_user_path
    user_path(session[:user_id])
  end

  def commentable
    params[:question_id] ?  Question.find(params[:question_id]) : Answer.find(params[:answer_id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @questions = @category.questions
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    user        = User.find(session[:user_id])
    question_id = params[:question_id]
    answer_id   = params[:answer_id]
    question_id ? commentable = Question.find(question_id) : commentable = Answer.find(answer_id)
    comment = Comment.new(content: params[:comment][:content], commentable: commentable, user: user )
    comment.save
    redirect_to :back
  end

  def index
    question = Question.find(params[:question_id])
    comments = Comment.find_by(commentable: question)
    render json: comments
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all.order(vote_count: :desc)
    # If you're going to branch logic based on Asynch, look at the respond_to
    #

    # BTW: This is crazy inefficient.  You're pulling the entire universe to
    # map though it, you can use SQL to do this faster.  Probably not a problem
    # today, but when you get to 50K questions, it will hurt.
    @questions = Question.all.includes("category").map{|ques| {id: ques.id, category: ques.category.name, title: ques.title, username: ques.user.username} }
    respond_to do |format|
      format.html
      format.json { @questions }
    end
  end

  def show
    @question = Question.with_all_relations(params[:id])
    @answer = Answer.new
  end

  def new
    @question = Question.new
    @categories = Category.all
  end

  def create
    params[:question][:user_id] = session[:user_id]
    Question.create(question_params)
    redirect_to curr_user_path
  end

  def recent
    @questions = Question.all.order(created_at: :desc)
    render 'questions/index'
  end

  def trending
    @questions = Question.trending
    render 'questions/index'
  end

  private

  def question_params
    params.require(:question).permit(:title, :content, :category_id, :user_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to curr_user_path if session[:user_id]
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_url
    else
      session[:message] = "invalid username and/or password"
      redirect_to new_session_path
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to user
    else
      key, value = user.errors.messages.first
      session[:message] = "#{key.to_s} #{value.first}"
      redirect_to new_user_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :email)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    vote = Vote.new(vote_params)
    vote[:user_id] = curr_user.id if curr_user

    if vote.save
      render json: {vote_count: vote.voteable.vote_count, status: 200}
    else
      render json: { error: vote.errors.values[0] }, status: 403
    end
  end

  private

  def vote_params
    params.permit(:voteable_id, :voteable_type, :direction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def curr_user
    User.find(session[:user_id]) if session[:user_id]
  end


  def curr_user_path
    user_path(session[:user_id])
  end


  def curr_session_path
    session_path(session[:user_id])
  end


end

app/views/answers/_answer.html.erb
<li class='list-group-item answer-detail'>
  <div class='row'>
    <div class='col-md-1'>
      <%= render partial: 'votes/new', locals: {vote_count: answer.vote_count, voteable_type: 'Answer', voteable_id: answer.id} %>
    </div>
    <div class='col-md-11'>
      <p><%= answer.content %></p>
      <strong><%= link_to answer.user.username, answer.user %></strong>
      <ul class='list-group'>
        <%= render answer.comments %>
      </ul>
      <%= render partial: 'comments/new', locals: {commentable: answer, comment: Comment.new}%>
    </div>
  </div>
</li>

app/views/answers/_new.html.erb
<div class="answer_form">
  <h3> Answer </h3>
  <%= form_for [question, answer] do |f| %>
    <%= f.text_area :content, placeholder: "Answer"%>
    <%= f.submit%>
  <%end%>
</div>

app/views/categories/index.html.erb
<h1>Categories</h1>
<ul class="list-group categories">
  <% @categories.each do |category| %>
    <li class="list-group-item">
      <h3><%= link_to category.name, category %></h3>
    </li>
  <% end %>
</ul>

app/views/categories/show.html.erb
<h1><%= @category.name %> Questions</h1>
<ul class="list-group">
  <%= render @questions %>
</ul>

app/views/comments/_comment.html.erb
<li class='list-group-item comment-detail'>
  <p><%= comment.content %></p>
  <strong><%= link_to comment.user.username, comment.user %></strong>
</li>

app/views/comments/_new.html.erb
<a href="#" class="post_comment"> Comment </a>
<%= form_for [commentable, comment] do |f| %>
  <%= f.text_area :content, placeholder: "Answer"%>
  <%= f.submit%>
<%end%>

app/views/layouts/_search_bar.html.erb
<form class="navbar-form search_form" role="search" id="search-bar">
  <div class="form-group">
    <input type="text" id ="search_request" name = "search_request" class="form-control" placeholder="Search...">
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>

app/views/layouts/_top_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'LambOverice', root_url, class: 'navbar-brand' %>
    </div>

    <ul class="nav navbar-nav navbar-left">
      <% if curr_user %>
        <li><%= link_to 'Ask', new_question_path %></li>
      <% end %>
      <li><%= link_to 'Categories', categories_path %></li>

    <ul class="nav navbar-nav navbar-right">
      <li><%= render 'layouts/search_bar' %></li>
      <% if curr_user %>
        <li><%= link_to 'My Account', curr_user_path %></li>
        <li><%= link_to 'Logout', curr_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Login', new_session_path %></li>
        <li><%= link_to 'Sign Up', new_user_path %></li>
      <% end %>
    </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StackOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/top_navbar' %>

  <div class='container-fluid' id='main-content'>
    <div class='container'>
      <div class="search_results">
        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/questions/_question.html.erb
<li class='list-group-item'>
  <div class='row'>
    <div class='col-md-1 list-vote-count'>
      <%= question.vote_count %>
    </div>
    <div class='col-md-11'>
      <h3><%= link_to question.title, question %></h3>
      <strong><%= link_to question.user.username, question.user %></strong>
    </div>
  </div>
</li>

app/views/questions/index.html.erb
<h1>Top Questions</h1>
<div class="btn-group" role="group">
  <%= link_to 'Karma', questions_path, class: 'btn btn-default' %>
  <%= link_to 'Recent', recent_questions_path, class: 'btn btn-default' %>
  <%= link_to 'Trending', trending_questions_path, class: 'btn btn-default' %>
</div>
<ul class='list-group'>
    <%= render @questions %>
</ul>

app/views/questions/new.html.erb
<div id="question_form" class="input-group">
  <%= form_for(@question) do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", id: "question-title" %><br/>

    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control", id: "question-content" %><br/>

    <%= f.label :category_id %><br/>
    <%= f.select :category_id do %>
        <% @categories.each do |category| %>
            <%= content_tag(:option, category.name, value: category.id) %>
        <% end %>
    <% end %><br/>

    <%= f.hidden_field :user_id %><br/>


    <button class="btn btn-default" id="preview-button">Preview</button>
    <%= f.submit "Create", class: "btn btn-default" %>
  <% end %>
</div>

<h1 id="preview-title">Question Preview</h1>
<div id="question-preview" class="panel panel-default">



</div>

app/views/questions/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class='row'>
      <div class='col-md-1 question-vote-buttons'>
        <%= render partial: 'votes/new', locals: {vote_count: @question.vote_count, voteable_type: 'Question', voteable_id: @question.id} %>
      </div>
      <div class='col-md-11'>
        <h1><%= @question.title %></h1>
        <%= link_to @question.category.name, @question.category %>
        <h5>by: <%= link_to @question.user.username, @question.user %></h5>
      </div>
  </div>

  <div class="panel-body">
    <%= @question.content %>
  </div>
  <ul id="question-comment-box">
  </ul>
</div>

<ul class="list-group">
  <%= render @question.answers.order(vote_count: :desc) %>
</ul>

<% if curr_user %>
  <div class="answer_form">
    <%= render partial: 'answers/new', locals: {answer: @answer, question: @question} %>
  </div>
<% end %>

app/views/users/new.html.erb
<div id="signup">

  <h1>Signup</h1>

  <%= form_for(@user) do |f| %>

    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :password %>
    <%= f.text_field :password %>

    <%= f.submit "Create Account" %>
  <% end %>

  <% if session[:message] %>
    <%= session[:message] %>
    <% session.delete(:message) %>
  <% end %>

</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-4">
    <h2><%= @user.username.capitalize %></h2>
  </div>
  <div class="col-md-4">
    <h2><span class="fa fa-star"></span><%= @user.karma %><h2>
  </div>
  <div class="col-md-4 panel panel-default">
    <h4>Questions: <%= @user.questions.count %><h4>
    <h4>Answers: </span><%= @user.answers.count %><h4>
    <h4>Comments: </span><%= @user.comments.count %><h4>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <h3>Questions</h3>
    <ul class="list-group">
      <% @user.questions.each do |question| %>
        <li class="list-group-item">
          <%= link_to question.title, question %>
          <% if curr_user && @user.id == curr_user.id %>
            <ul class="list-group">
              <% question.answers.each do |answer| %>
                <li class="list-group-item">
                  <p><%= answer.content %></p>
                  <%= link_to answer.user.username, answer.user %>
                </li>
              <% end %>
            </ul>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="col-md-6">
    <h3>Answers</h3>
    <ul class="list-group">
      <% @user.answers.each do |answer| %>
        <li class="list-group-item">
          <%= link_to answer.question.title, answer %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/votes/_new.html.erb
<div class='btn-group-vertical' role='group'>
  <button type='button' class='btn btn-default btn-sm vote-buttons' data-direction='Up' data-voteabletype='<%= voteable_type %>' data-voteableid='<%= voteable_id %>' >
    <span class='fa fa-caret-square-o-up'></span>
  </button>

  <button type='button' class='btn btn-default btn-sm' disabled>
    <span class='vote-count' id='<%= "#{voteable_type}-#{voteable_id}-votecount" %>'><%= vote_count %></span>
  </button>

  <button type='button' class='btn btn-default btn-sm vote-buttons' data-direction='Down' data-voteabletype='<%= voteable_type %>' data-voteableid='<%= voteable_id %>'>
    <span class='fa fa-caret-square-o-down'></span>
  </button>
</div>